# Data Cleaning
---

## Load Dataset
---

In [ ]:
import os
import pandas as pd

BASE_DIR = os.path.dirname(os.getcwd())

RAW_DIR = os.path.join(BASE_DIR, "data", "raw")

customers = pd.read_csv(
    os.path.join(RAW_DIR, "customers.csv"),
    parse_dates=["signup_date", "last_login_date"]
)

subscriptions = pd.read_csv(
    os.path.join(RAW_DIR, "subscriptions.csv"),
    parse_dates=["start_date", "end_date"]
)

payments = pd.read_csv(
    os.path.join(RAW_DIR, "payments.csv"),
    parse_dates=["payment_date"]
)

usage = pd.read_csv(
    os.path.join(RAW_DIR, "product_usage.csv"),
    parse_dates=["usage_date"]
)

tickets = pd.read_csv(
    os.path.join(RAW_DIR, "support_tickets.csv"),
    parse_dates=["created_date"]
)

print("Semua data mentah berhasil dimuat tanpa error!")

Semua data mentah berhasil dimuat tanpa error!

## Referential Integrity Check
---

In [2]:
# Payment
payments[
    ~payments["customer_id"]
    .isin(customers["customer_id"])
]

Empty DataFrame
Columns: [payment_id, customer_id, payment_date, amount, payment_status, payment_method]
Index: []

In [3]:
# usage
usage[
    ~usage["customer_id"]
    .isin(customers["customer_id"])
]

Empty DataFrame
Columns: [usage_id, customer_id, usage_date, login_count, session_duration, feature_used]
Index: []

In [4]:
# ticket
tickets[
    ~tickets["customer_id"]
    .isin(customers["customer_id"])
]

Empty DataFrame
Columns: [ticket_id, customer_id, created_date, issue_type, resolution_time_hours, ticket_status]
Index: []

In [5]:
# subscription
subscriptions[
    ~subscriptions["customer_id"]
    .isin(customers["customer_id"])
]

Empty DataFrame
Columns: [subscription_id, customer_id, plan, contract_type, start_date, end_date, status, monthly_fee, tenure_months]
Index: []

## Business Rules Validation
---

In [6]:
# Rule 1
subscriptions[
    subscriptions["start_date"]
    > subscriptions["end_date"]
]

Empty DataFrame
Columns: [subscription_id, customer_id, plan, contract_type, start_date, end_date, status, monthly_fee, tenure_months]
Index: []

In [7]:
# Rule 2
payments[
    payments["amount"] <= 0
]

Empty DataFrame
Columns: [payment_id, customer_id, payment_date, amount, payment_status, payment_method]
Index: []

In [8]:
# Rule 3
usage[
    usage["session_duration"] <= 0
]

Empty DataFrame
Columns: [usage_id, customer_id, usage_date, login_count, session_duration, feature_used]
Index: []

In [9]:
# Rule 4
customers[
    customers["age"] < 18
]

Empty DataFrame
Columns: [customer_id, signup_date, country, age, gender, acquisition_channel, company_size, industry, last_login_date]
Index: []

In [10]:
# Rule 5
subscriptions[
    ~subscriptions["status"]
    .isin(["Active", "Churned"])
]

Empty DataFrame
Columns: [subscription_id, customer_id, plan, contract_type, start_date, end_date, status, monthly_fee, tenure_months]
Index: []

## Save Processed Data
---

In [11]:
import os

BASE_DIR = os.path.dirname(os.getcwd())

PROCESSED_DIR = os.path.join(BASE_DIR, "data", "processed")

os.makedirs(PROCESSED_DIR, exist_ok=True)

customers.to_csv(
    os.path.join(PROCESSED_DIR, "customers_clean.csv"),
    index=False
)

subscriptions.to_csv(
    os.path.join(PROCESSED_DIR, "subscriptions_clean.csv"),
    index=False
)

payments.to_csv(
    os.path.join(PROCESSED_DIR, "payments_clean.csv"),
    index=False
)

usage.to_csv(
    os.path.join(PROCESSED_DIR, "product_usage_clean.csv"),
    index=False
)

tickets.to_csv(
    os.path.join(PROCESSED_DIR, "support_tickets_clean.csv"),
    index=False
)

print(f"Semua data bersih berhasil disimpan ke: {PROCESSED_DIR}")

Semua data bersih berhasil disimpan ke: c:\VSCode\customer-churn-analytics\data\processed